; Moonshine ESP-C3 - DIY variant based on ESP32-C3 + E22-400M33S (433MHz)
[env:moonshine_ESP_C3]
extends = esp32c3_base
board = esp32-c3-devkitm-1
board_level = pr
build_flags =
  ${esp32c3_base.build_flags}
  -D PRIVATE_HW
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -I variants/esp32c3/diy/moonshine_ESP_C3
