; Moonshine NRF52 node - DIY variant based on RF-BM-ND05 nRF52840 module
[env:moonshine_NRF52_node]
extends = nrf52840_base
board = adafruit_feather_nrf52840
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/moonshine_NRF52
  -D PRIVATE_HW
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/moonshine_NRF52>
debug_tool = jlink
