; Moonshine NRF52 node - DIY variant based on RF-BM-ND05 nRF52840 module
[env:moonshine_NRF52_node]
extends = nrf52840_base
board = adafruit_feather_nrf52840
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/moonshine_NRF52
  -D PRIVATE_HW
  -D USE_SEGGER
  -D MESHTASTIC_EXCLUDE_I2C=1
  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -D MESHTASTIC_EXCLUDE_INPUTBROKER=1
  -D MESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -D MESHTASTIC_EXCLUDE_MAGNETOMETER=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/moonshine_NRF52>
debug_tool = jlink
