; Moonshine NRF52 mini - minimal DIY variant (nRF52840 + RA-01S-P SX1262)
[env:moonshine_NRF52_node_mini]
extends = nrf52840_base
board = adafruit_feather_nrf52840
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/moonshine_NRF52_mini
  -D PRIVATE_HW
  -D MESHTASTIC_EXCLUDE_I2C=1
  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -D MESHTASTIC_EXCLUDE_INPUTBROKER=1
  -D MESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -D MESHTASTIC_EXCLUDE_MAGNETOMETER=1
  -D MESHTASTIC_EXCLUDE_GPS=1
  -D MESHTASTIC_EXCLUDE_SCREEN=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/moonshine_NRF52_mini>
debug_tool = jlink
